# -*- coding: utf-8 -*-
"""Day4-Christ_College_HousePrice_Appl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bgog9HUbaD5_b3xnbCfPhipOshzGrDIR
"""

import streamlit as st
import joblib

# Load trained model
model = joblib.load("house_price_model.pkl")

# Title
st.title("House Price Predictor")

# Get house area from user
area = st.number_input(
    "Enter House Area (SQ FT):",
    min_value=1,
    max_value=5000,
    value=1000
)


if st.button("Predict Price"):

    if 1 <= area <= 3000:
        price = model.predict([[area]])
        st.success(f"Predicted House Price: ₹{price[0]:.2f} Lakhs")
    else:
        st.error("Please enter house area between 1 and 3000 SQ FT.")
    
# if area > 3000:
#     st.error("House area has crossed the maximum limit of 3000 SQ FT.")

# # Prediction button
# if st.button("Predict Price"):

#     price = model.predict([[area]])

#     st.success(f"Predicted House Price: ₹{price[0]:.2f} Lakhs")
